### PR TITLE
Update CreateTensorPileupFromCffi.py

### PR DESCRIPTION
**Pull request by AJTDaedalus**
Changed deprecated np.int to int.

### CODE REVIEW

**Comment by zhengzhenxian** [comment]
@AJTDaedalus 
Thanks so much for the fix!

**Comment by caspargross** [comment]
Can you update the bioconda package with the fix? 
Running version clair3 v0.1.12 from bioconda still gives the same error from the original issue for me

**Comment by aquaskyline** [comment]
Sure, we will update all installation options by next Monday.

**Comment by caspargross** [comment]
@aquaskyline Thank you for the quick reply. As a side note: The bioconda packages for the older versions (0.1.10 and 0.1.11) are also broken because of the fixed dependency on pigz==v2.4 which is not available on bioconda or conda-forge anymore.

**Pull request merged**
